apiVersion: v1
kind: Secret
metadata:
  name: securedox-secrets
  namespace: securedox
type: Opaque
stringData:
  AUTH_JWT_SECRET: replace-me-with-a-local-minikube-secret
  POSTGRES_PASSWORD: securedox_local_pw
