"""Initial schema: tenants, documents, extracted fields, validation results, audit.

Hand-written rather than autogenerated so the constraints that encode the
domain rules — the state-machine enum, the tenant-scoped dedupe index, the
append-only audit grant — carry comments explaining why they exist.

Revision ID: 0001_initial
Revises:
Created: 2026-01-01 00:00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Enum values must match `securedox_shared.enums` exactly — the API publishes
# these strings in its OpenAPI schema and the worker writes them back.
DOCUMENT_TYPE = postgresql.ENUM(
    "LOAN", "INSURANCE", "MEDICAL", "ONBOARDING", name="document_type", create_type=False
)
DOCUMENT_STATUS = postgresql.ENUM(
    "RECEIVED",
    "QUEUED",
    "EXTRACTING",
    "VALIDATING",
    "REVIEW_REQUIRED",
    "VALIDATED",
    "REJECTED",
    "FAILED",
    "QUARANTINED",
    name="document_status",
    create_type=False,
)
VALIDATION_STATUS = postgresql.ENUM(
    "PASS", "WARN", "FAIL", name="validation_status", create_type=False
)
SEVERITY = postgresql.ENUM(
    "INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL", name="severity", create_type=False
)
FIELD_SOURCE = postgresql.ENUM(
    "OCR", "MANUAL", "DERIVED", name="field_source", create_type=False
)
AUDIT_ACTION = postgresql.ENUM(
    "DOCUMENT_UPLOADED",
    "DOCUMENT_QUEUED",
    "EXTRACTION_STARTED",
    "EXTRACTION_COMPLETED",
    "VALIDATION_COMPLETED",
    "DOCUMENT_REJECTED",
    "DOCUMENT_SUBMITTED",
    "DOCUMENT_QUARANTINED",
    "FIELD_CORRECTED",
    "PROCESSING_FAILED",
    name="audit_action",
    create_type=False,
)

_ALL_ENUMS = (
    DOCUMENT_TYPE,
    DOCUMENT_STATUS,
    VALIDATION_STATUS,
    SEVERITY,
    FIELD_SOURCE,
    AUDIT_ACTION,
)


def upgrade() -> None:
    bind = op.get_bind()
    for enum in _ALL_ENUMS:
        enum.create(bind, checkfirst=True)

    op.create_table(
        "tenants",
        sa.Column("id", sa.String(64), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "max_upload_bytes", sa.Integer(), nullable=False, server_default="10485760"
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_tenants"),
        sa.CheckConstraint("id = lower(id)", name="ck_tenants_id_lowercase"),
        sa.CheckConstraint("length(id) >= 2", name="ck_tenants_id_min_length"),
    )
    op.create_index("ix_tenants_created_at", "tenants", ["created_at"])

    op.create_table(
        "documents",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("tenant_id", sa.String(64), nullable=False),
        sa.Column("document_type", DOCUMENT_TYPE, nullable=False),
        sa.Column("status", DOCUMENT_STATUS, nullable=False, server_default="RECEIVED"),
        sa.Column("original_filename", sa.String(255), nullable=False),
        sa.Column("mime_type", sa.String(127), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(64), nullable=False),
        sa.Column("storage_key", sa.String(512), nullable=False),
        sa.Column("correlation_id", sa.String(64), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("ocr_provider", sa.String(32), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rejection_reason", sa.String(1000), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_documents"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_documents_tenant_id_tenants",
            # RESTRICT, not CASCADE: deleting a tenant must not silently erase
            # the documents a regulator may still ask about.
            ondelete="RESTRICT",
        ),
        # The same bytes from one tenant is a duplicate, not a new document.
        sa.UniqueConstraint("tenant_id", "checksum_sha256", name="uq_documents_tenant_checksum"),
        sa.CheckConstraint("size_bytes > 0", name="ck_documents_size_positive"),
        sa.CheckConstraint(
            "page_count IS NULL OR page_count >= 0", name="ck_documents_page_count_non_negative"
        ),
    )
    op.create_index("ix_documents_tenant_id", "documents", ["tenant_id"])
    op.create_index("ix_documents_created_at", "documents", ["created_at"])
    op.create_index("ix_documents_correlation_id", "documents", ["correlation_id"])
    # Serves the list view's three shapes: tenant, tenant+status, and the
    # keyset ordering — one index instead of three.
    op.create_index(
        "ix_documents_tenant_status_created",
        "documents",
        ["tenant_id", "status", "created_at"],
    )

    op.create_table(
        "extracted_fields",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("document_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("field_name", sa.String(64), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("source", FIELD_SOURCE, nullable=False, server_default="OCR"),
        sa.Column("is_pii", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("original_value", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_extracted_fields"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name="fk_extracted_fields_document_id_documents",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "document_id", "field_name", name="uq_extracted_fields_document_field"
        ),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0", name="ck_extracted_fields_confidence_range"
        ),
    )
    op.create_index("ix_extracted_fields_document_id", "extracted_fields", ["document_id"])
    op.create_index("ix_extracted_fields_created_at", "extracted_fields", ["created_at"])

    op.create_table(
        "validation_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("document_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("rule_id", sa.String(32), nullable=False),
        sa.Column("field_name", sa.String(64), nullable=False),
        sa.Column("status", VALIDATION_STATUS, nullable=False),
        sa.Column("severity", SEVERITY, nullable=False),
        sa.Column("message", sa.String(500), nullable=False),
        sa.Column("observed", sa.Text(), nullable=True),
        sa.Column("is_blocking", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_validation_results"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name="fk_validation_results_document_id_documents",
            ondelete="CASCADE",
        ),
        # One outcome per rule per document: re-running validation updates in
        # place rather than accumulating contradictory history.
        sa.UniqueConstraint(
            "document_id", "rule_id", name="uq_validation_results_document_rule"
        ),
    )
    op.create_index("ix_validation_results_document_id", "validation_results", ["document_id"])
    op.create_index("ix_validation_results_created_at", "validation_results", ["created_at"])
    op.create_index(
        "ix_validation_results_rule_status", "validation_results", ["rule_id", "status"]
    )

    op.create_table(
        "audit_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("tenant_id", sa.String(64), nullable=False),
        sa.Column("document_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action", AUDIT_ACTION, nullable=False),
        sa.Column("actor", sa.String(128), nullable=False),
        sa.Column("correlation_id", sa.String(64), nullable=False),
        sa.Column(
            "detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}"
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_audit_events"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_audit_events_tenant_id_tenants",
            ondelete="RESTRICT",
        ),
        # Deliberately no FK to documents: an audit row outlives its subject.
    )
    op.create_index("ix_audit_events_created_at", "audit_events", ["created_at"])
    op.create_index("ix_audit_events_tenant_created", "audit_events", ["tenant_id", "created_at"])
    op.create_index("ix_audit_events_document", "audit_events", ["document_id"])
    op.create_index("ix_audit_events_correlation", "audit_events", ["correlation_id"])

    # Append-only enforcement at the database, not just in application code:
    # the app role can insert and read audit rows but never modify them, so a
    # code-level bug (or a compromised service) cannot rewrite the evidence.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION securedox_reject_audit_mutation()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'audit_events is append-only (attempted %)', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_events_append_only
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION securedox_reject_audit_mutation();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_events_append_only ON audit_events;")
    op.execute("DROP FUNCTION IF EXISTS securedox_reject_audit_mutation();")

    op.drop_table("audit_events")
    op.drop_table("validation_results")
    op.drop_table("extracted_fields")
    op.drop_table("documents")
    op.drop_table("tenants")

    bind = op.get_bind()
    for enum in reversed(_ALL_ENUMS):
        enum.drop(bind, checkfirst=True)
